---
version: '2.4'
services:
  bitbucket-server:
    image: 'atlassian/bitbucket-server:${BITBUCKET_VERSION:-5.12.0}'
    environment:
      ELASTICSEARCH_ENABLED: 'false'
      JMX_ENABLED: 'true'
    ports:
      # JMX
      - '3333:3333'
      # HTTP
      - '7990:7990'
      # SSH
      - '7999:7999'
  postgres:
    image: 'postgres:${POSTGRESQL_VERSION:-10.4-alpine}'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-sekrit}'
